name: lower
on: [workflow_dispatch, pull_request, push]
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  lower-pr:
    uses: tek/hix/.github/workflows/lower-pr.yml@main
    secrets:
      cachix_key: ${{ secrets.CACHIX_SIGNING_KEY }}
